package one.modality.event.server.rest.bunnystream;

import dev.webfx.platform.ast.ReadOnlyAstArray;
import dev.webfx.platform.ast.ReadOnlyAstObject;
import dev.webfx.platform.async.Future;
import dev.webfx.platform.boot.spi.ApplicationModuleBooter;
import dev.webfx.platform.console.Console;
import dev.webfx.platform.util.Numbers;
import dev.webfx.platform.util.vertx.VertxInstance;
import dev.webfx.stack.orm.entity.EntityStore;
import io.vertx.core.http.HttpServerResponse;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;
import io.vertx.ext.web.handler.BodyHandler;
import one.modality.base.shared.entities.Event;
import one.modality.base.shared.entities.Organization;
import one.modality.base.shared.entities.ScheduledItem;

import java.util.ArrayList;
import java.util.List;

import static dev.webfx.platform.util.http.HttpResponseStatus.*;

/**
 * Server-side REST proxy that drives the publish-video flow on the Bunny.net Stream API.
 *
 * <p>The REST surface is intentionally tiny — four control-plane endpoints. The video
 * bytes themselves never traverse this server: the browser uploads directly to
 * {@code bunny.net} via the TUS protocol using the short-lived signature returned by
 * {@code /rest/videos/init}, which keeps egress costs off our infrastructure.
 *
 * <ul>
 *   <li>{@code GET    /rest/videos/library?scheduledItemId=N}<br>
 *       Resolves credentials from DB, calls Bunny GET {@code /library/{lib}} for the
 *       human-readable name, and reports either {@code {ok:true, libraryName, …}} or
 *       {@code {ok:false, missingFields:[…]}} for the React empty-state UX.</li>
 *   <li>{@code POST   /rest/videos/init?scheduledItemId=N}  body {@code {"title":"…"}}<br>
 *       Asks Bunny to allocate a video, computes the TUS auth signature, returns
 *       {@code {guid, libraryId, pullZoneId, authSignature, authExpire}}.</li>
 *   <li>{@code GET    /rest/videos/status?scheduledItemId=N&guid=G}<br>
 *       Proxies Bunny's video status; on first FINISHED or first available resolution,
 *       triggers the idempotent Media insert + ScheduledItem.published flip
 *       (see {@link BunnyStreamPublisher}).</li>
 *   <li>{@code DELETE /rest/videos/abort?scheduledItemId=N&guid=G}<br>
 *       Cleans up an aborted/failed Bunny video record so we don't leave orphans.</li>
 * </ul>
 *
 * <p><b>Credentials:</b> resolved per-request from the database by walking
 * ScheduledItem → Event → Organization. The chain pulls
 * {@code Event.vodBunnyLibraryId}, {@code Event.vodBunnyPullZoneId} and
 * {@code Organization.bunnyApiKey} (the latter is the single account-level key
 * shared with audio/storage features). Generic {@code getStringFieldValue}
 * accessors are used because typed getters/setters for these fields are not
 * yet generated by WebFX.
 */
public final class BunnyStreamRestService implements ApplicationModuleBooter {

    private static final String LIBRARY_PATH = "/rest/videos/library";
    private static final String INIT_PATH    = "/rest/videos/init";
    private static final String STATUS_PATH  = "/rest/videos/status";
    private static final String ABORT_PATH   = "/rest/videos/abort";

    // Library Management tab — event-scoped read/delete surface over Bunny.
    private static final String LIBRARY_INFO_PATH   = "/rest/videos/library-info";
    private static final String LIBRARY_VIDEOS_PATH = "/rest/videos/library-videos";
    private static final String LIBRARY_VIDEO_PATH  = "/rest/videos/library-video";

    /** Bunny's library-videos paging cap. Anything larger is silently clamped server-side
     *  by Bunny, but we clamp here to keep the client honest. */
    private static final int MAX_VIDEOS_PER_PAGE = 1000;
    private static final int DEFAULT_VIDEOS_PER_PAGE = 100;

    /** Bunny Stream numeric statuses (https://docs.bunny.net/reference/video_getvideo). */
    private static final int BUNNY_STATUS_FINISHED = 4;
    private static final int BUNNY_STATUS_ERROR = 5;
    private static final int BUNNY_STATUS_UPLOAD_FAILED = 6;

    /** Codes the React layer maps to translated rows in the missing-credentials panel.
     *  The contract is intentionally explicit — server picks the codes, React decides
     *  the copy. Keeps the i18n wiring simple. */
    private static final String MISSING_API_KEY    = "organization.bunnyApiKey";
    private static final String MISSING_LIBRARY    = "event.vodBunnyLibraryId";
    private static final String MISSING_PULL_ZONE  = "event.vodBunnyPullZoneId";

    @Override
    public String getModuleName() {
        return "kbs-server-bunnystream-plugin";
    }

    @Override
    public int getBootLevel() {
        return COMMUNICATION_REGISTER_BOOT_LEVEL;
    }

    @Override
    public void bootModule() {
        // The try/catch is permanent. If anything inside throws, the exception
        // would bubble up to VertxApplicationBooterVerticle.start() and fail the
        // verticle silently — main exits, event loop threads keep the JVM alive
        // on EPoll.wait, port 8080 never gets bound, no rolling-log entry. The
        // catch below makes that case visible on stderr (which IntelliJ captures)
        // and on the rolling logger.
        try {
            Router router = VertxInstance.getHttpRouter();

            router.get(LIBRARY_PATH).handler(this::handleLibrary);
            // BodyHandler is required to parse the JSON body on the init endpoint.
            router.post(INIT_PATH)
                    .handler(BodyHandler.create())
                    .handler(this::handleInit);
            router.get(STATUS_PATH).handler(this::handleStatus);
            router.delete(ABORT_PATH).handler(this::handleAbort);

            // Library Management tab (event-scoped).
            router.get(LIBRARY_INFO_PATH).handler(this::handleLibraryInfo);
            router.get(LIBRARY_VIDEOS_PATH).handler(this::handleLibraryVideos);
            router.get(LIBRARY_VIDEO_PATH).handler(this::handleLibraryVideoGet);
            router.delete(LIBRARY_VIDEO_PATH).handler(this::handleLibraryVideoDelete);

            Console.log("[BUNNY-STREAM] REST routes registered: "
                    + LIBRARY_PATH + ", " + INIT_PATH + ", " + STATUS_PATH + ", " + ABORT_PATH
                    + ", " + LIBRARY_INFO_PATH + ", " + LIBRARY_VIDEOS_PATH + ", " + LIBRARY_VIDEO_PATH
                    + " (GET/DELETE)");
            Console.log("[BUNNY-STREAM] Credentials resolved per-request from DB "
                    + "(Event.vodBunnyLibraryId/vodBunnyPullZoneId, Organization.bunnyApiKey).");
        } catch (Throwable t) {
            System.err.println("[BUNNY-STREAM] bootModule FAILED: " + t);
            t.printStackTrace(System.err);
            Console.error("[BUNNY-STREAM] bootModule FAILED", t);
            throw t;
        }
    }

    // ─── /rest/videos/library ──────────────────────────────────────────────

    /**
     * Drives both the missing-credentials empty state and the "Library: {name}" chip
     * on the React Publish Video tab. Always returns {@code 200 OK} — the React
     * layer reads {@code ok}/{@code missingFields}/{@code error} to drive its UI.
     */
    private void handleLibrary(RoutingContext ctx) {
        Long sessionId = parseLong(ctx.request().getParam("scheduledItemId"));
        if (sessionId == null) {
            sendError(ctx, BAD_REQUEST_400, "missing scheduledItemId");
            return;
        }
        loadCredentials(sessionId).onComplete(ar -> {
            if (ar.failed()) {
                sendError(ctx, INTERNAL_SERVER_ERROR_500, ar.cause().getMessage());
                return;
            }
            BunnyCredentials creds = ar.result();
            List<String> missing = creds.missingFields();
            if (!missing.isEmpty()) {
                sendJson(ctx, OK_200, jsonLibraryMissing(missing));
                return;
            }
            BunnyStreamApiClient.getLibrary(creds.libraryId, creds.apiKey)
                    .onSuccess(json -> {
                        // Bunny library API field is "Name" (capital N); fall back gracefully.
                        String name = json.getString("Name");
                        if (isBlank(name)) name = json.getString("name");
                        sendJson(ctx, OK_200, jsonLibraryOk(creds.libraryId, creds.pullZoneId, name));
                    })
                    .onFailure(err -> {
                        String msg = err.getMessage();
                        sendJson(ctx, OK_200, jsonLibraryError(
                                msg == null || msg.isEmpty()
                                        ? "Bunny rejected the credentials (likely 401 Unauthorized)."
                                        : msg));
                    });
        });
    }

    // ─── /rest/videos/init ─────────────────────────────────────────────────

    private void handleInit(RoutingContext ctx) {
        Long sessionId = parseLong(ctx.request().getParam("scheduledItemId"));
        if (sessionId == null) {
            sendError(ctx, BAD_REQUEST_400, "missing scheduledItemId");
            return;
        }
        String title = readTitle(ctx);
        if (title == null || title.isEmpty()) {
            sendError(ctx, BAD_REQUEST_400, "missing title");
            return;
        }
        loadCredentials(sessionId).compose(creds -> {
            if (!creds.isComplete()) {
                return Future.failedFuture(missingMessage(creds.missingFields()));
            }
            return BunnyStreamApiClient.createVideo(creds.libraryId, creds.apiKey, title)
                    .map(guid -> {
                        BunnyStreamApiClient.TusAuth auth = BunnyStreamApiClient.buildTusSignature(creds.libraryId, creds.apiKey, guid);
                        return jsonInitResponse(guid, creds.libraryId, creds.pullZoneId, auth);
                    });
        })
        .onSuccess(json -> sendJson(ctx, OK_200, json))
        .onFailure(err -> sendError(ctx, INTERNAL_SERVER_ERROR_500, err.getMessage()));
    }

    /** Title can come from JSON body or from the {@code title} query parameter (fallback for clients
     *  that prefer not to send a body on POST). */
    private static String readTitle(RoutingContext ctx) {
        String fromQuery = ctx.request().getParam("title");
        if (fromQuery != null && !fromQuery.isEmpty()) return fromQuery.trim();
        try {
            String bodyText = ctx.body() != null ? ctx.body().asString() : null;
            if (bodyText == null || bodyText.isEmpty()) return null;
            // Avoid a JSON parser dep for one field — accept either a raw string or a tiny {"title":"…"} object.
            String trimmed = bodyText.trim();
            if (trimmed.startsWith("\"") && trimmed.endsWith("\""))
                return unescapeSimple(trimmed.substring(1, trimmed.length() - 1));
            int titleStart = trimmed.indexOf("\"title\"");
            if (titleStart < 0) return null;
            int colon = trimmed.indexOf(':', titleStart);
            int firstQuote = trimmed.indexOf('"', colon);
            if (firstQuote < 0) return null;
            int endQuote = trimmed.indexOf('"', firstQuote + 1);
            // Re-scan to skip escaped quotes
            while (endQuote > 0 && trimmed.charAt(endQuote - 1) == '\\')
                endQuote = trimmed.indexOf('"', endQuote + 1);
            if (endQuote < 0) return null;
            return unescapeSimple(trimmed.substring(firstQuote + 1, endQuote));
        } catch (Exception e) {
            return null;
        }
    }

    // ─── /rest/videos/status ───────────────────────────────────────────────

    private void handleStatus(RoutingContext ctx) {
        Long sessionId = parseLong(ctx.request().getParam("scheduledItemId"));
        String guid = ctx.request().getParam("guid");
        if (sessionId == null || guid == null || guid.isEmpty()) {
            sendError(ctx, BAD_REQUEST_400, "missing scheduledItemId or guid");
            return;
        }
        long sessionIdValue = sessionId;
        loadCredentials(sessionIdValue).compose(creds -> {
            if (!creds.isComplete()) {
                return Future.failedFuture(missingMessage(creds.missingFields()));
            }
            return BunnyStreamApiClient.getVideo(creds.libraryId, creds.apiKey, guid)
                    .compose(json -> {
                        int status = Numbers.intValue(json.get("status"));
                        int encodeProgress = Numbers.intValue(json.get("encodeProgress"));
                        long length = Numbers.longValue(json.get("length"));
                        // Bunny's "length" is duration in seconds; convert to millis for the Media row.
                        long durationMillis = length > 0 ? length * 1000L : 0L;
                        String[] resolutions = parseResolutions(json.getString("availableResolutions"));
                        String mapped = mapStatus(status);

                        // LR-first publish: Bunny encodes resolutions lowest-first, so the
                        // session is viewable as soon as ONE resolution lands — we don't
                        // wait for status=FINISHED (=all resolutions). The publisher's own
                        // idempotency guard short-circuits subsequent polls.
                        boolean shouldPublish = status == BUNNY_STATUS_FINISHED || resolutions.length > 0;
                        if (shouldPublish) {
                            return BunnyStreamPublisher.finalizeFinishedUpload(
                                            sessionIdValue, guid, creds.pullZoneId, durationMillis > 0 ? durationMillis : null)
                                    .map(v -> jsonStatusResponse(mapped, encodeProgress, length, durationMillis, true, resolutions));
                        }
                        return Future.succeededFuture(jsonStatusResponse(mapped, encodeProgress, length, durationMillis, false, resolutions));
                    });
        })
        .onSuccess(body -> sendJson(ctx, OK_200, body))
        .onFailure(err -> sendError(ctx, INTERNAL_SERVER_ERROR_500, err.getMessage()));
    }

    /** Bunny returns availableResolutions as a comma-separated string (e.g. "240p,360p,480p"),
     *  or {@code null} / empty when no resolution has finished yet. Package-private so the
     *  Library Management handlers can reuse the same parser. */
    static String[] parseResolutions(String csv) {
        if (csv == null || csv.isEmpty()) return new String[0];
        String[] parts = csv.split(",");
        int kept = 0;
        for (String p : parts) {
            if (p != null && !p.trim().isEmpty()) parts[kept++] = p.trim();
        }
        if (kept == parts.length) return parts;
        String[] out = new String[kept];
        System.arraycopy(parts, 0, out, 0, kept);
        return out;
    }

    /** Map Bunny's numeric status to the stable string token the React layer keys off.
     *  Package-private so the Library Management handlers reuse the same mapping —
     *  divergence between Publish and Library would silently break status badges. */
    static String mapStatus(int bunnyStatus) {
        switch (bunnyStatus) {
            case 0:  return "CREATED";
            case 1:  return "UPLOADED";
            case 2:  return "PROCESSING";
            case 3:  return "TRANSCODING";
            case 4:  return "FINISHED";
            case BUNNY_STATUS_ERROR:         return "ERROR";
            case BUNNY_STATUS_UPLOAD_FAILED: return "UPLOAD_FAILED";
            case 7:  return "JIT_SEGMENTING";
            default: return "UNKNOWN";
        }
    }

    // ─── /rest/videos/abort ────────────────────────────────────────────────

    private void handleAbort(RoutingContext ctx) {
        Long sessionId = parseLong(ctx.request().getParam("scheduledItemId"));
        String guid = ctx.request().getParam("guid");
        if (sessionId == null || guid == null || guid.isEmpty()) {
            sendError(ctx, BAD_REQUEST_400, "missing scheduledItemId or guid");
            return;
        }
        loadCredentials(sessionId).compose(creds -> {
            if (!creds.isComplete()) {
                return Future.failedFuture(missingMessage(creds.missingFields()));
            }
            return BunnyStreamApiClient.deleteVideo(creds.libraryId, creds.apiKey, guid);
        })
        .onSuccess(v -> ctx.response().setStatusCode(NO_CONTENT_204).end())
        .onFailure(err -> sendError(ctx, INTERNAL_SERVER_ERROR_500, err.getMessage()));
    }

    // ─── /rest/videos/library-info ─────────────────────────────────────────

    /**
     * Drives the stats banner and the missing-credentials empty state on the React
     * Library Management tab. Always returns {@code 200 OK} — the React layer reads
     * {@code ok}/{@code missingFields}/{@code error} to drive its UI, mirroring the
     * {@link #handleLibrary} contract.
     *
     * <p>The Bunny library JSON exposes {@code Name}, {@code StorageUsage} (bytes),
     * {@code TrafficUsage} (bytes), and {@code VideoCount} — enough for the four-tile
     * stats banner; we don't need the heavier {@code /statistics} time series for v1.
     */
    private void handleLibraryInfo(RoutingContext ctx) {
        Long eventId = parseLong(ctx.request().getParam("eventId"));
        if (eventId == null) {
            sendError(ctx, BAD_REQUEST_400, "missing eventId");
            return;
        }
        loadCredentialsByEventId(eventId).onComplete(ar -> {
            if (ar.failed()) {
                sendError(ctx, INTERNAL_SERVER_ERROR_500, ar.cause().getMessage());
                return;
            }
            BunnyCredentials creds = ar.result();
            List<String> missing = creds.missingFields();
            if (!missing.isEmpty()) {
                sendJson(ctx, OK_200, jsonLibraryMissing(missing));
                return;
            }
            BunnyStreamApiClient.getLibrary(creds.libraryId, creds.apiKey)
                    .onSuccess(json -> {
                        String name = json.getString("Name");
                        if (isBlank(name)) name = json.getString("name");
                        long storageBytes   = Numbers.longValue(json.get("StorageUsage"));
                        long bandwidthBytes = Numbers.longValue(json.get("TrafficUsage"));
                        int videoCount      = Numbers.intValue(json.get("VideoCount"));
                        sendJson(ctx, OK_200, jsonLibraryInfoOk(
                                creds.libraryId, creds.pullZoneId, name,
                                storageBytes, bandwidthBytes, videoCount));
                    })
                    .onFailure(err -> {
                        String msg = err.getMessage();
                        sendJson(ctx, OK_200, jsonLibraryError(
                                msg == null || msg.isEmpty()
                                        ? "Bunny rejected the credentials (likely 401 Unauthorized)."
                                        : msg));
                    });
        });
    }

    // ─── /rest/videos/library-videos ───────────────────────────────────────

    /**
     * Paged list of videos in the Event's Bunny library. Pagination is preserved
     * end-to-end so the React grid can virtualise / lazy-load if the library grows
     * large; default {@code perPage=100} matches Bunny's own dashboard.
     *
     * <p>Returns {@code 400 Bad Request} when credentials are missing — the React
     * tab calls {@code library-info} first to render the missing-credentials empty
     * state, so reaching this endpoint without credentials is a programming error.
     */
    private void handleLibraryVideos(RoutingContext ctx) {
        Long eventId = parseLong(ctx.request().getParam("eventId"));
        if (eventId == null) {
            sendError(ctx, BAD_REQUEST_400, "missing eventId");
            return;
        }
        int page = clampPositive(parseInt(ctx.request().getParam("page")), 1);
        int perPage = clampRange(parseInt(ctx.request().getParam("perPage")),
                DEFAULT_VIDEOS_PER_PAGE, 1, MAX_VIDEOS_PER_PAGE);
        loadCredentialsByEventId(eventId).compose(creds -> {
            if (!creds.isComplete()) {
                return Future.failedFuture(missingMessage(creds.missingFields()));
            }
            return BunnyStreamApiClient.listVideos(creds.libraryId, creds.apiKey, page, perPage)
                    .map(BunnyStreamRestService::jsonLibraryVideosResponse);
        })
        .onSuccess(body -> sendJson(ctx, OK_200, body))
        .onFailure(err -> sendError(ctx, INTERNAL_SERVER_ERROR_500, err.getMessage()));
    }

    // ─── GET /rest/videos/library-video ────────────────────────────────────

    /**
     * Refresh a single video's metadata. Used by the React grid to re-poll just the
     * card whose status changed, instead of re-fetching the whole page — keeps the
     * UI smooth when a 100-video library is still encoding a few items.
     */
    private void handleLibraryVideoGet(RoutingContext ctx) {
        Long eventId = parseLong(ctx.request().getParam("eventId"));
        String guid = ctx.request().getParam("guid");
        if (eventId == null || guid == null || guid.isEmpty()) {
            sendError(ctx, BAD_REQUEST_400, "missing eventId or guid");
            return;
        }
        loadCredentialsByEventId(eventId).compose(creds -> {
            if (!creds.isComplete()) {
                return Future.failedFuture(missingMessage(creds.missingFields()));
            }
            return BunnyStreamApiClient.getVideo(creds.libraryId, creds.apiKey, guid)
                    .map(json -> {
                        StringBuilder sb = new StringBuilder();
                        appendVideoJson(sb, json);
                        return sb.toString();
                    });
        })
        .onSuccess(body -> sendJson(ctx, OK_200, body))
        .onFailure(err -> sendError(ctx, INTERNAL_SERVER_ERROR_500, err.getMessage()));
    }

    // ─── DELETE /rest/videos/library-video ─────────────────────────────────

    /**
     * Delete a video from the Bunny library. The Media row, if any, is cleaned up
     * client-side via {@code useChangeSet().delete('Media', …)} so that the existing
     * EventBus authorization + audit path covers the DB write — this route is
     * Bunny-only.
     */
    private void handleLibraryVideoDelete(RoutingContext ctx) {
        Long eventId = parseLong(ctx.request().getParam("eventId"));
        String guid = ctx.request().getParam("guid");
        if (eventId == null || guid == null || guid.isEmpty()) {
            sendError(ctx, BAD_REQUEST_400, "missing eventId or guid");
            return;
        }
        loadCredentialsByEventId(eventId).compose(creds -> {
            if (!creds.isComplete()) {
                return Future.failedFuture(missingMessage(creds.missingFields()));
            }
            return BunnyStreamApiClient.deleteVideo(creds.libraryId, creds.apiKey, guid);
        })
        .onSuccess(v -> ctx.response().setStatusCode(NO_CONTENT_204).end())
        .onFailure(err -> sendError(ctx, INTERNAL_SERVER_ERROR_500, err.getMessage()));
    }

    // ─── Credential resolution ─────────────────────────────────────────────

    /**
     * Walk ScheduledItem → Event → Organization to resolve the three credentials.
     * Returns a never-null {@link BunnyCredentials} carrier; caller checks
     * {@link BunnyCredentials#isComplete()} / {@link BunnyCredentials#missingFields()}
     * to surface a user-friendly empty state.
     *
     * <p>The DSQL select pulls both the direct {@code event.*} chain AND the
     * {@code programScheduledItem.event.*} chain; video sessions are typically
     * children of a program ScheduledItem, so we want the EntityStore to load
     * the program's event in the same round-trip and pick whichever side has
     * the event populated.
     */
    private static Future<BunnyCredentials> loadCredentials(long sessionId) {
        return EntityStore.create().<ScheduledItem>executeQuery(
                        "select id," +
                                " event.vodBunnyLibraryId, event.vodBunnyPullZoneId," +
                                " event.organization.bunnyApiKey," +
                                " programScheduledItem.event.vodBunnyLibraryId," +
                                " programScheduledItem.event.vodBunnyPullZoneId," +
                                " programScheduledItem.event.organization.bunnyApiKey" +
                                " from ScheduledItem where id=$1",
                        sessionId)
                .map(rows -> {
                    if (rows.isEmpty()) {
                        // Surface a hard error (caller wraps via Future) — this isn't a
                        // missing-field condition; the session id itself is bogus.
                        throw new RuntimeException("ScheduledItem " + sessionId + " not found");
                    }
                    ScheduledItem si = rows.get(0);
                    Event event = si.getEvent() != null ? si.getEvent() : programEvent(si);
                    if (event == null) {
                        throw new RuntimeException("ScheduledItem " + sessionId + " has no associated Event");
                    }
                    String libraryId  = event.getStringFieldValue("vodBunnyLibraryId");
                    String pullZoneId = event.getStringFieldValue("vodBunnyPullZoneId");
                    Organization org = event.getOrganization();
                    String apiKey = org == null ? null : org.getStringFieldValue("bunnyApiKey");
                    return new BunnyCredentials(
                            isBlank(libraryId) ? null : libraryId.trim(),
                            isBlank(pullZoneId) ? null : pullZoneId.trim(),
                            isBlank(apiKey) ? null : apiKey.trim());
                });
    }

    private static Event programEvent(ScheduledItem si) {
        ScheduledItem program = si.getProgramScheduledItem();
        return program == null ? null : program.getEvent();
    }

    /**
     * Event-scoped credential resolver for the Library Management tab. Mirrors
     * {@link #loadCredentials(long)} but skips the ScheduledItem hop — the library
     * is configured at the Event level so the React tab passes {@code eventId}
     * directly. Same {@link BunnyCredentials} carrier and same missing-field codes
     * keep the React layer's empty-state UX in sync between the Publish and Library
     * tabs.
     */
    private static Future<BunnyCredentials> loadCredentialsByEventId(long eventId) {
        return EntityStore.create().<Event>executeQuery(
                        "select id, vodBunnyLibraryId, vodBunnyPullZoneId," +
                                " organization.bunnyApiKey" +
                                " from Event where id=$1",
                        eventId)
                .map(rows -> {
                    if (rows.isEmpty()) {
                        throw new RuntimeException("Event " + eventId + " not found");
                    }
                    Event event = rows.get(0);
                    String libraryId  = event.getStringFieldValue("vodBunnyLibraryId");
                    String pullZoneId = event.getStringFieldValue("vodBunnyPullZoneId");
                    Organization org = event.getOrganization();
                    String apiKey = org == null ? null : org.getStringFieldValue("bunnyApiKey");
                    return new BunnyCredentials(
                            isBlank(libraryId) ? null : libraryId.trim(),
                            isBlank(pullZoneId) ? null : pullZoneId.trim(),
                            isBlank(apiKey) ? null : apiKey.trim());
                });
    }

    /** Build a flat user-facing message from the structured missing-field codes —
     *  used for {@code /init}, {@code /status}, {@code /abort} which return text
     *  errors. {@code /library} returns the structured list directly. */
    private static String missingMessage(List<String> missing) {
        if (missing.contains(MISSING_API_KEY)) return "Bunny API key missing on the organization (set Organization.bunnyApiKey).";
        if (missing.contains(MISSING_LIBRARY)) return "Bunny library ID missing on the event (set Event.vodBunnyLibraryId).";
        if (missing.contains(MISSING_PULL_ZONE)) return "Bunny pull zone ID missing on the event (set Event.vodBunnyPullZoneId).";
        return "Bunny credentials are not configured.";
    }

    // ─── Helpers ───────────────────────────────────────────────────────────

    private static boolean isBlank(String s) { return s == null || s.trim().isEmpty(); }

    private static Long parseLong(String s) {
        if (s == null) return null;
        try { return Long.parseLong(s.trim()); } catch (NumberFormatException e) { return null; }
    }

    private static Integer parseInt(String s) {
        if (s == null) return null;
        try { return Integer.parseInt(s.trim()); } catch (NumberFormatException e) { return null; }
    }

    private static int clampPositive(Integer value, int defaultValue) {
        if (value == null || value < 1) return defaultValue;
        return value;
    }

    private static int clampRange(Integer value, int defaultValue, int min, int max) {
        if (value == null) return defaultValue;
        if (value < min) return min;
        if (value > max) return max;
        return value;
    }

    private static String unescapeSimple(String s) {
        return s.replace("\\\"", "\"").replace("\\\\", "\\")
                .replace("\\n", "\n").replace("\\r", "\r").replace("\\t", "\t");
    }

    private static String jsonInitResponse(String guid, String libraryId, String pullZoneId, BunnyStreamApiClient.TusAuth auth) {
        return "{"
                + "\"guid\":\"" + BunnyStreamApiClient.escapeJson(guid) + "\","
                + "\"libraryId\":\"" + BunnyStreamApiClient.escapeJson(libraryId) + "\","
                + "\"pullZoneId\":\"" + BunnyStreamApiClient.escapeJson(pullZoneId) + "\","
                + "\"authSignature\":\"" + auth.signature + "\","
                + "\"authExpire\":" + auth.expire
                + "}";
    }

    private static String jsonStatusResponse(String status, int encodeProgress, long length, long durationMillis, boolean published, String[] availableResolutions) {
        StringBuilder sb = new StringBuilder("{");
        sb.append("\"status\":\"").append(status).append("\",");
        sb.append("\"encodeProgress\":").append(encodeProgress).append(",");
        sb.append("\"length\":").append(length).append(",");
        sb.append("\"durationMillis\":").append(durationMillis).append(",");
        sb.append("\"published\":").append(published).append(",");
        sb.append("\"availableResolutions\":[");
        for (int i = 0; i < availableResolutions.length; i++) {
            if (i > 0) sb.append(',');
            sb.append('"').append(BunnyStreamApiClient.escapeJson(availableResolutions[i])).append('"');
        }
        sb.append(']');
        sb.append('}');
        return sb.toString();
    }

    private static String jsonLibraryOk(String libraryId, String pullZoneId, String libraryName) {
        StringBuilder sb = new StringBuilder("{");
        sb.append("\"ok\":true");
        sb.append(",\"libraryId\":\"").append(BunnyStreamApiClient.escapeJson(libraryId)).append('"');
        sb.append(",\"pullZoneId\":\"").append(BunnyStreamApiClient.escapeJson(pullZoneId)).append('"');
        sb.append(",\"libraryName\":\"")
                .append(BunnyStreamApiClient.escapeJson(libraryName == null ? "" : libraryName))
                .append('"');
        sb.append('}');
        return sb.toString();
    }

    private static String jsonLibraryMissing(List<String> missing) {
        StringBuilder sb = new StringBuilder("{");
        sb.append("\"ok\":false,\"missingFields\":[");
        for (int i = 0; i < missing.size(); i++) {
            if (i > 0) sb.append(',');
            sb.append('"').append(BunnyStreamApiClient.escapeJson(missing.get(i))).append('"');
        }
        sb.append("]}");
        return sb.toString();
    }

    private static String jsonLibraryError(String error) {
        return "{\"ok\":false,\"error\":\""
                + BunnyStreamApiClient.escapeJson(error == null ? "" : error)
                + "\"}";
    }

    /** Stats-banner payload: {@code Name}/{@code StorageUsage}/{@code TrafficUsage}/
     *  {@code VideoCount} from Bunny, plus the {@code pullZoneId} the React side needs
     *  to build thumbnail URLs without a second round-trip. */
    private static String jsonLibraryInfoOk(String libraryId, String pullZoneId, String libraryName,
                                            long storageBytes, long bandwidthBytes, int videoCount) {
        StringBuilder sb = new StringBuilder("{");
        sb.append("\"ok\":true");
        sb.append(",\"libraryId\":\"").append(BunnyStreamApiClient.escapeJson(libraryId)).append('"');
        sb.append(",\"libraryName\":\"")
                .append(BunnyStreamApiClient.escapeJson(libraryName == null ? "" : libraryName))
                .append('"');
        sb.append(",\"pullZoneId\":\"").append(BunnyStreamApiClient.escapeJson(pullZoneId)).append('"');
        sb.append(",\"storageBytes\":").append(storageBytes);
        sb.append(",\"bandwidthBytes\":").append(bandwidthBytes);
        sb.append(",\"videoCount\":").append(videoCount);
        sb.append('}');
        return sb.toString();
    }

    /** Map Bunny's {@code {items, totalItems, currentPage, itemsPerPage}} response to
     *  our reduced {@code {items, totalItems, currentPage, itemsPerPage}} envelope —
     *  preserves pagination so the React grid can fetch additional pages without
     *  re-deriving the cursor. */
    private static String jsonLibraryVideosResponse(ReadOnlyAstObject json) {
        StringBuilder sb = new StringBuilder("{\"items\":[");
        ReadOnlyAstArray items = json.getArray("items");
        if (items != null) {
            for (int i = 0; i < items.size(); i++) {
                if (i > 0) sb.append(',');
                ReadOnlyAstObject item = items.getObject(i);
                appendVideoJson(sb, item);
            }
        }
        sb.append("],\"totalItems\":").append(Numbers.longValue(json.get("totalItems")));
        sb.append(",\"currentPage\":").append(Numbers.intValue(json.get("currentPage")));
        sb.append(",\"itemsPerPage\":").append(Numbers.intValue(json.get("itemsPerPage")));
        sb.append('}');
        return sb.toString();
    }

    /** Serialise a single Bunny video item to the React-facing JSON shape. Kept as a
     *  shared helper so the {@code library-videos} list and the {@code library-video}
     *  single-fetch produce byte-identical card payloads. The Bunny field for per-video
     *  bandwidth is {@code totalBandwidthUsed}; we fall back to {@code 0} when absent
     *  rather than emit {@code null} so the React layer can do plain numeric maths. */
    static void appendVideoJson(StringBuilder sb, ReadOnlyAstObject item) {
        if (item == null) {
            sb.append("{}");
            return;
        }
        int statusInt = Numbers.intValue(item.get("status"));
        String status = mapStatus(statusInt);
        int encodeProgress = Numbers.intValue(item.get("encodeProgress"));
        long length = Numbers.longValue(item.get("length"));
        long storageSize = Numbers.longValue(item.get("storageSize"));
        long bandwidth = Numbers.longValue(item.get("totalBandwidthUsed"));
        String[] resolutions = parseResolutions(item.getString("availableResolutions"));

        sb.append('{');
        sb.append("\"guid\":\"").append(BunnyStreamApiClient.escapeJson(nullToEmpty(item.getString("guid")))).append('"');
        sb.append(",\"title\":\"").append(BunnyStreamApiClient.escapeJson(nullToEmpty(item.getString("title")))).append('"');
        sb.append(",\"status\":\"").append(status).append('"');
        sb.append(",\"encodeProgress\":").append(encodeProgress);
        sb.append(",\"length\":").append(length);
        sb.append(",\"storageSize\":").append(storageSize);
        sb.append(",\"bandwidth\":").append(bandwidth);
        sb.append(",\"thumbnailFileName\":\"")
                .append(BunnyStreamApiClient.escapeJson(nullToEmpty(item.getString("thumbnailFileName"))))
                .append('"');
        sb.append(",\"dateUploaded\":\"")
                .append(BunnyStreamApiClient.escapeJson(nullToEmpty(item.getString("dateUploaded"))))
                .append('"');
        sb.append(",\"availableResolutions\":[");
        for (int i = 0; i < resolutions.length; i++) {
            if (i > 0) sb.append(',');
            sb.append('"').append(BunnyStreamApiClient.escapeJson(resolutions[i])).append('"');
        }
        sb.append(']');
        sb.append('}');
    }

    private static String nullToEmpty(String s) {
        return s == null ? "" : s;
    }

    private static void sendJson(RoutingContext ctx, int statusCode, String body) {
        HttpServerResponse response = ctx.response();
        response.putHeader("Content-Type", "application/json; charset=utf-8");
        response.setStatusCode(statusCode).end(body);
    }

    private static void sendError(RoutingContext ctx, int statusCode, String message) {
        Console.log("[BUNNY-STREAM] " + statusCode + " — " + message);
        sendJson(ctx, statusCode, "{\"error\":\"" + BunnyStreamApiClient.escapeJson(message == null ? "" : message) + "\"}");
    }

    /** Per-request credential carrier — never shared across threads. */
    private static final class BunnyCredentials {
        final String libraryId;
        final String pullZoneId;
        final String apiKey;

        BunnyCredentials(String libraryId, String pullZoneId, String apiKey) {
            this.libraryId = libraryId;
            this.pullZoneId = pullZoneId;
            this.apiKey = apiKey;
        }

        boolean isComplete() {
            return apiKey != null && libraryId != null && pullZoneId != null;
        }

        /** Stable codes that the React layer maps to translated rows. */
        List<String> missingFields() {
            List<String> out = new ArrayList<>(3);
            if (apiKey == null)     out.add(MISSING_API_KEY);
            if (libraryId == null)  out.add(MISSING_LIBRARY);
            if (pullZoneId == null) out.add(MISSING_PULL_ZONE);
            return out;
        }
    }
}
