package one.modality.crm.shared.services.authn;

/**
 * Asks the server to start enrolling an authenticator app (TOTP, RFC 6238) on the logged-in account.
 *
 * <p>Sent on the {@code updateCredentials} path so the caller's principal is available server-side —
 * only an authenticated, non-support-view session may plant a factor on its own account, and the
 * account is taken from that principal, never from anything the client sends. The reply is a JSON
 * string {@code {otpauthUri, secret, issuer, username}}: the secret is generated by the server,
 * stored encrypted, and stored UNCONFIRMED.
 *
 * <p>Unconfirmed is the point: a row only becomes a factor after {@link ConfirmTotpEnrolmentCredentials}
 * proves the app holds the same secret. A mistyped or half-scanned secret therefore costs a repeat
 * enrolment, not a lockout — which is why nothing may ever require a factor that was never confirmed.
 *
 * @param label the app or device name the owner typed (≤ 64 chars), for their own listing
 *
 * @author Claude Code
 */
public record StartTotpEnrolmentCredentials(String label) {
}
