-- V0030: move the registration team's manual "sold out" control out of ItemPolicy.
--
-- forceSoldOut never belonged in the policy tables, and five things say so:
--   • different writer — the registration team, not the admins who configure policy;
--   • different lifecycle — operational, flipped during the booking window, not at setup;
--   • a natural scope that is always event+item and never organization or eventType;
--   • it is the ONLY field registration writes; everything else in a policy is read-only to them;
--   • and it structurally blocks centralising policy into wider scopes, which is the whole point of
--     the V0025-V0029 work: both the KBS3 hook and KBS2's ResourcesGraphicActivity find their rows
--     with `where scope.event = ?`, so the button exists only where an event-scoped ItemPolicy
--     happens to exist. Delete those duplicated rows and the control silently disappears.
--
-- The row's PRESENCE means "forced sold out" — there is no boolean. Toggling on inserts, off
-- deletes. That keeps the normal case storing nothing, leaves no meaningless soldOut=false rows
-- behind, and sidesteps the NOT NULL DEFAULT trap that V0026 and V0029 had to undo.
--
-- site is nullable: null means "wherever this item is offered for this event", which is what the
-- KBS3 hook already assumed by ignoring site entirely. KBS2 reads scope.site.id and keys its UI by
-- (site, item), so it writes the site explicitly. A reader matches on event + item, and on site
-- only when the row names one.
--
-- item_policy.force_sold_out is deliberately KEPT for now. KBS2 still writes it until
-- ResourcesGraphicActivity ships against this table, and dropping the column before that would
-- break KBS2 on the first KBS3 deploy. A later migration drops it once KBS2 is out.

CREATE TABLE IF NOT EXISTS sold_out_item (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id integer NOT NULL REFERENCES event(id),
    item_id  integer NOT NULL REFERENCES item(id),
    site_id  integer REFERENCES site(id)
);

-- One row per thing that can be sold out. NULLS NOT DISTINCT so a second site-less row for the same
-- (event, item) collides rather than silently duplicating.
CREATE UNIQUE INDEX IF NOT EXISTS sold_out_item_event_item_site_idx
    ON sold_out_item (event_id, item_id, site_id) NULLS NOT DISTINCT;

CREATE INDEX IF NOT EXISTS sold_out_item_event_idx ON sold_out_item (event_id);

-- Carry over what registration has already set. Only event-scoped policies can have been reachable
-- by either button, so only those are migrated; the site comes from the policy's own scope.
INSERT INTO sold_out_item (event_id, item_id, site_id)
SELECT ps.event_id, ip.item_id, ps.site_id
FROM item_policy ip
JOIN policy_scope ps ON ps.id = ip.scope_id
WHERE ip.force_sold_out AND ps.event_id IS NOT NULL
ON CONFLICT DO NOTHING;

COMMENT ON TABLE sold_out_item IS
    'Registration''s manual "sold out" override: the row''s presence forces an item sold out for an '
    'event, whatever its computed availability. Operational state, deliberately not in the policy '
    'tables — different writer, different lifecycle, and always event-scoped.';

COMMENT ON COLUMN sold_out_item.site_id IS
    'NULL = every site this item is offered at for the event.';
