-- Single-use invite tokens for the room-mate booking flow (docs/room-mate-booking-plan.md,
-- steps 4-5, D5). A room booker mints a token bound to their OWN accommodation line and sends the
-- resulting link to the person sharing their room; that person books, and the server consumes the
-- token to link the two bookings (share_mate_owner_document_line_id).
--
-- SERVER-INTERNAL. This table is deliberately NOT in the domain model: the server reads and writes
-- it with raw SQL, so it never appears on the client-queryable DQL surface. That matters because
-- unauthenticated reads are currently possible (security report A1); keeping the table off that
-- surface, AND storing only a HASH of the token, means a leaked read cannot yield a usable link.
--
-- Single-use and expiry are enforced by the claim statement, not a clock the app has to check:
-- consuming is a conditional UPDATE ... WHERE used_date IS NULL AND expires_date > now(), which a
-- row lock makes atomic, so a token resolves at most once (D5).
CREATE TABLE IF NOT EXISTS mate_invite_token (
    id                       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- sha-256 hex of the raw token. The raw token exists only in the invite URL; it is never stored.
    token_hash               character(64) NOT NULL UNIQUE,
    -- The room booker's accommodation line the mate is invited to share, and its event (denormalised
    -- so the claim needs no join and the token-event == mate-event check is a single comparison).
    owner_document_line_id   integer NOT NULL REFERENCES document_line (id),
    event_id                 integer NOT NULL REFERENCES event (id),
    -- The account that minted it, for audit; null is not expected today (minting is account-gated).
    creator_account_id       integer REFERENCES frontend_account (id),
    created_date             timestamp with time zone DEFAULT now() NOT NULL,
    -- Event end plus a grace window, set at mint. A token never resolves after this (backstop clock).
    expires_date             timestamp with time zone NOT NULL,
    -- Set when the token is consumed; its presence is what makes the token single-use.
    used_date                timestamp with time zone,
    -- The mate line that consumed it, for audit; set best-effort after the mate booking commits.
    used_by_document_line_id integer REFERENCES document_line (id)
);

COMMENT ON TABLE mate_invite_token IS
    'Single-use room-share invite tokens (hashed). Server-internal: not in the domain model, raw-SQL only.';

-- The claim looks a token up by its hash; that is the only hot path.
CREATE UNIQUE INDEX IF NOT EXISTS mate_invite_token_hash_idx ON mate_invite_token (token_hash);
