package one.modality.ecommerce.document.service;

import dev.webfx.platform.async.Future;
import dev.webfx.stack.orm.domainmodel.DataSourceModel;

/**
 * Server-side extension point: stores a BOOKING_ACCESS magic link record in the
 * database after a guest booking is successfully submitted.
 *
 * The token is pre-generated by ServerDocumentServiceProvider and written onto the
 * document (document.magic_link_token) before the INSERT, so the DB bracket pattern
 * can resolve [bookingUrl] to the magic-link URL at email-generation time. This
 * method is called after the INSERT to persist the corresponding magic_link record.
 *
 * The confirmation email itself is handled entirely by the existing database-driven
 * letter system (trigger_document_generate_mails_on_booking + interpret_brackets).
 *
 * The interface lives in modality-ecommerce-document-service so that
 * ServerDocumentServiceProvider can call it without a circular dependency on
 * modality-crm. The implementation is in the CRM magic-link plugin and discovered
 * via ServiceLoader.
 *
 * @author Bruno Salmon
 */
public interface GuestBookingAccessService {

    /**
     * Persist the magic_link record for a guest booking and link it to the booking cart.
     * The cart link enables /cart/:cartUuid authentication and invalidation when the
     * guest later creates an account.
     *
     * @param token          the UUID token already written onto document.magic_link_token
     * @param documentPk     primary key of the newly created Document (used as requestedPath)
     * @param cartPk         primary key of the booking cart to link to the magic link
     * @param personEmail    guest email address
     * @param personLang     guest preferred language (2-char code, e.g. "en")
     * @param clientOrigin   frontend origin used to compose magic_link.link, e.g. "https://kbs.kadampa.net"
     * @param dataSourceModel data source to write to
     * @return future that completes when the magic_link record is stored and cart linked
     */
    Future<Void> registerBookingAccessMagicLink(
        String token,
        Object documentPk,
        Object cartPk,
        String personEmail,
        String personLang,
        String clientOrigin,
        DataSourceModel dataSourceModel
    );
}
